version: '3'
services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /root/geth-work
    working_dir: /root/geth-work
    tty: true
    ports:
      - 3000:3000
      - 8545:8545
    environment:
      - METEOR_ALLOW_SUPERUSER=true
